name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.13, 3.14]
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up poetry
        run: |
          pip install poetry
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local

      - name: Run tests
        run: make test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Set up poetry
        run: |
          pip install poetry
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local

      - name: Run pre-commit
        uses: https://git.iamthefij.com/iamthefij/pre-commit-action@v3.0.2
